name = "esl-scoping-review"
main = "src/worker.js"
compatibility_date = "2024-09-23"

# Configures the Worker to serve static assets from the "public" directory
[assets]
directory = "public"
binding = "ASSETS"